### PR TITLE
Add NetBSD

### PR DESCRIPTION
**Pull request by 0323pin**
http://mail-index.netbsd.org/pkgsrc-changes/2022/09/10/msg260340.html

### CODE REVIEW

**Comment by 0323pin** [comment]
> to install it should run as root user?

Like on any other system, you need root permissions to install.
Yes, you can use `su`, `sudo`, `doas`, `please`, ... but, these need to be installed and configured first.
Except for `su`, which we ship with by default.

**Comment by arthurhenrique** [comment]
> > to install it should run as root user?
> 
> Like on any other system, you need root permissions to install. Yes, you can use `su`, `sudo`, `doas`, `please`, ... but, these need to be installed and configured first. Except for `su`, which we ship with by default.

nice job. thx

**Review by arthurhenrique — APPROVED** [review]
Nice job. I think would be great add on apt, apk repos too. Thx

**Comment by 0323pin** [comment]
> Nice job. I think would be great add on apt, apk repos too. Thx

You're welcome. Let's hope a dev from Debian finds it and creates a package.

**Pull request merged**
